from simulation.gym.E import E

DEMO_ENV_1 = {
    'action': E.A.CHOOSE_LOT_FOR_FREE_MACHINE,
    'state_components': (
        E.A.L4M.S.MACHINE.SETUP_PROCESSING_RATIO,
        E.A.L4M.S.MACHINE.IDLE_RATIO,
        E.A.L4M.S.MACHINE.MAINTENANCE.NEXT,
        E.A.L4M.S.OPERATION_TYPE.NO_LOTS_PER_BATCH,
        E.A.L4M.S.OPERATION_TYPE.CR.MAX,
        E.A.L4M.S.OPERATION_TYPE.FREE_SINCE.MAX,
        E.A.L4M.S.OPERATION_TYPE.SETUP.MIN_RUNS_OK,
        E.A.L4M.S.OPERATION_TYPE.SETUP.NEEDED,
        E.A.L4M.S.OPERATION_TYPE.SETUP.LAST_SETUP_TIME,
    )
}
